repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-yaml

  - repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
      - id: seed-isort-config

  - repo: https://github.com/pre-commit/mirrors-isort
    rev: v5.10.1
    hooks:
      - id: isort
        exclude: "docs/.*"

  - repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
      - id: mypy
        exclude: "docs/.*"
        # verbose: true
        entry: bash -c 'mypy "$@" || true' --

  - repo: https://github.com/psf/black
    rev: 23.3.0 # Replace by any tag/version: https://github.com/psf/black/tags
    hooks:
      - id: black
        name: black
        exclude: ".depreciated/.*|.old_work/.*|docs/.*"
        # exclude: ^.depreciated/

  - repo: https://github.com/PyCQA/flake8
    rev: 6.0.0
    hooks:
      - id: flake8
        exclude: ".depreciated/.*|.old_work/.*"

default_language_version:
  python: python3
