repos:
-   repo: https://github.com/asottile/seed-isort-config
    rev: v2.2.0
    hooks:
    -   id: seed-isort-config

-   repo: https://github.com/pre-commit/mirrors-isort
    rev: v4.3.21
    hooks:
      - id: isort

-   repo: https://github.com/pre-commit/mirrors-mypy
    rev: v0.782
    hooks:
    -   id: mypy
        verbose: true
        entry: bash -c 'mypy "$@" || true' --

-   repo: https://github.com/psf/black
    rev: 2471b9256d9d9dfea1124d20072201693b9b0865
    hooks:
      - id: black
        name: black

-   repo: https://gitlab.com/pycqa/flake8
    rev: 3.8.3
    hooks:
    -   id: flake8

default_language_version:
    python: python3
    # python: python3.7
