version: "3"

services:
  slurm:
    build: .
    hostname: slurmctl
    stdin_open: true
    tty: true
    ports:
      - "4002:4001" # public IPFS Port
    volumes:
      - ~/docker/volumes/lib:/var/lib/slurmd
      - ~/docker/volumes/spool:/var/spool/slurm
      - ~/docker/volumes/log:/var/log/slurm
      - ~/docker/volumes/db:/var/lib/mysql
      - ./docker/config:/workspace/config

  # requester:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./docker/requester
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - "4101:4001" # Public IPFS Port
