version: '3'

services:
  slurm:
    build: .
    hostname: slurmctl
    stdin_open: true
    tty: true
    ports:
      - "4001:4001" # Public IPFS Port
      # - "6001:6001"
      # - "6002:6002"
    volumes:
      - ~/docker/volumes/lib:/var/lib/slurmd
      - ~/docker/volumes/spool:/var/spool/slurm
      - ~/docker/volumes/log:/var/log/slurm
      - ~/docker/volumes/db:/var/lib/mysql
  # slurm:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./docker/provider
  #   hostname: slurmctl
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - "4001:4001" # Public IPFS Port
  #   volumes:
  #     - ./volumes/lib:/var/lib/slurmd
  #     - ./volumes/spool:/var/spool/slurm
  #     - ./volumes/log:/var/log/slurm
  #     - ./volumes/db:/var/lib/mysql
  # requester:
  #   build:
  #     dockerfile: Dockerfile
  #     context: ./docker/requester
  #   stdin_open: true
  #   tty: true
  #   ports:
  #     - "4002:4002" # Public IPFS Port
